### PR TITLE
Kubernetes/Jenkins

### PR DESCRIPTION
**Pull request by Jlucky94**

### CODE REVIEW

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Comment by Jlucky94** [comment]
run build production

**Review by alexsharich — APPROVED** [review]

**Pull request merged**
